version: 0.2

phases:

  install:
    runtime-versions:
      java: corretto17

  pre-build:
    commands:
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 225187408292.dkr.ecr.us-east-1.amazonaws.com
  
  build:
    commands:
      - echo Build started
      - mvn clean install
      - docker build -t first-maven .
      - docker tag first-maven:latest 225187408292.dkr.ecr.us-east-1.amazonaws.com/first-maven:latest
      - docker push 225187408292.dkr.ecr.us-east-1.amazonaws.com/first-maven:latest

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - target/surefire-reports/*.xml
    - target/*.jar


  reports:
    junit_reports:
      files:
      - target/surefire-reports/*.xml
