version: 0.2

env:
  variables:
    REPOSITORY_NAME: maven-testing

phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 225187408292.dkr.ecr.ap-south-1.amazonaws.com
    

  build:
    commands:
      - echo Build Maven project
      - mvn clean package

      - echo Build Docker image
      - docker build -t $REPOSITORY_NAME .

      - echo Tag Docker image
      - docker tag $REPOSITORY_NAME:latest 225187408292.dkr.ecr.ap-south-1.amazonaws.com/$REPOSITORY_NAME:latest

  post_build:
    commands:
      - echo Push Docker image
      - docker push 225187408292.dkr.ecr.ap-south-1.amazonaws.com/$REPOSITORY_NAME:latest
