version: 0.2

env:
  variables:
    REPOSITORY_NAME: maven-testing
    REGION: ap-south-1

phases:

  pre_build:
    commands:
      - echo Clean the target folder using maven clean command
      - mvn clean package
    

  build:
    commands:
      - echo testing started
      - mvn test
      - echo Build Maven project
      - mvn install


  post_build:
    commands:
      - echo store artifact in the S3 bucket
      - aws s3 cp target/*.jar s3://todaytask-225187408292-us-east-1-an
      - echo test reports store in s3 bucket
      - aws s3 cp target/surefire-reports/ s3://todaytask-225187408292-us-east-1-an/ --recursive
